"""
backend/services/pdf_report_service.py

Race Strategy Report Compiler for F1 PitWall AI.

Generates HTML/PDF race strategy reports including session metadata, driver classification,
tire stint timeline summary, and AI strategy recommendations.
"""

from typing import Dict, Any, List, Optional
from datetime import datetime

from backend.utils.logger import get_logger

logger = get_logger(__name__)


def generate_race_report_html(
    summary: Dict[str, Any],
    drivers: List[Dict[str, Any]],
    strategy_recommendation: Optional[Dict[str, Any]] = None,
) -> str:
    """Compile a styled HTML race strategy report."""
    year = summary.get("Year", 2024)
    event_name = summary.get("EventName", "Grand Prix")
    session_type = summary.get("SessionType", "R")
    circuit = summary.get("Circuit", "F1 Track")
    air_temp = summary.get("AirTemp", 25.0)
    track_temp = summary.get("TrackTemp", 38.0)

    driver_rows = ""
    for d in drivers[:10]:
        pos = d.get("Position", "-")
        code = d.get("DriverCode") or d.get("Abbreviation", "DRV")
        name = d.get("FullName", code)
        team = d.get("TeamName", "-")
        points = d.get("Points", 0)
        driver_rows += f"<tr><td>{pos}</td><td><strong>{code}</strong></td><td>{name}</td><td>{team}</td><td>{points}</td></tr>"

    strat_section = ""
    if strategy_recommendation:
        strat_section = f"""
        <div class="card">
            <h3>🤖 Recommended Pit Strategy</h3>
            <p><strong>Pit Window:</strong> {strategy_recommendation.get('recommended_pit_window', 'N/A')}</p>
            <p><strong>Suggested Compound:</strong> {strategy_recommendation.get('suggested_compound', 'N/A')}</p>
            <p><strong>Urgency:</strong> {strategy_recommendation.get('urgency', 'N/A')}</p>
            <p><em>{strategy_recommendation.get('explanation', '')}</em></p>
        </div>
        """

    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>F1 PitWall AI — Strategy Report ({year} {event_name})</title>
    <style>
        body {{ font-family: 'Helvetica Neue', Arial, sans-serif; background: #0d0d0d; color: #f0f0f0; padding: 20px; }}
        h1, h2, h3 {{ color: #E10600; margin-bottom: 5px; }}
        .header {{ border-bottom: 2px solid #E10600; padding-bottom: 10px; margin-bottom: 20px; }}
        .meta-table {{ width: 100%; border-collapse: collapse; margin-bottom: 20px; }}
        .meta-table td {{ padding: 8px; border: 1px solid #222; background: #141414; }}
        .card {{ background: #141414; border: 1px solid #222; border-radius: 8px; padding: 15px; margin-bottom: 20px; }}
        table.results {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
        table.results th {{ background: #222; color: #E10600; text-align: left; padding: 8px; }}
        table.results td {{ padding: 8px; border-bottom: 1px solid #222; }}
        .footer {{ font-size: 0.8rem; color: #666; text-align: center; margin-top: 30px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🏎️ F1 PITWALL AI — RACE STRATEGY REPORT</h1>
        <p>{year} {event_name} ({session_type}) · Generated {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    </div>

    <table class="meta-table">
        <tr>
            <td><strong>Event:</strong> {event_name}</td>
            <td><strong>Circuit:</strong> {circuit}</td>
            <td><strong>Session:</strong> {session_type}</td>
        </tr>
        <tr>
            <td><strong>Air Temp:</strong> {air_temp} °C</td>
            <td><strong>Track Temp:</strong> {track_temp} °C</td>
            <td><strong>Driver Count:</strong> {len(drivers)}</td>
        </tr>
    </table>

    {strat_section}

    <div class="card">
        <h3>🏁 Top Classification Standings</h3>
        <table class="results">
            <thead>
                <tr><th>Pos</th><th>Code</th><th>Name</th><th>Team</th><th>Points</th></tr>
            </thead>
            <tbody>
                {driver_rows}
            </tbody>
        </table>
    </div>

    <div class="footer">
        Generated by F1 PitWall AI &mdash; AI-assisted decision support using public historical F1 data. Not an official F1 tool.
    </div>
</body>
</html>
"""
    return html
